[package]
name = "rusted-ruins-geom"
version = "1.0.0"
edition = "2021"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]

[lib]
name = "rusted_ruins_geom"
crate-type = ["rlib"]

[dependencies]
serde = "1"
serde_derive = "1"
thiserror = "1"
