dialog-choice-exit = Exit
dialog-choice-newgame = New Game
dialog-choice-loadgame = Load Game
dialog-choice-close = Close
dialog-choice-exit_game = Exit Game
dialog-choice-save_game = Save Game
creation-start = Start
tile-menu-down-stairs = Go down the stairs
tile-menu-enter-site = Enter this site
tile-menu-exit-to-region-map = Exit to region map
tile-menu-infomation = Infomation
tile-menu-move-to-next-map = Move to next map
tile-menu-up-stairs = Go up the stairs
