creation-start = Start
dialog-choice-exit = Exit
dialog-choice-exit_game = Exit Game
dialog-choice-loadgame = Load Game
dialog-choice-newgame = New Game
dialog-choice-save_game = Save Game
dialog-choice-restart = Restart
dialog-button-cancel = Cancel
dialog-button-exit = Exit
dialog-button-save = Save
dialog-button-title_screen = Title Screen
equip_menu-information = Information
equip_menu-remove = Remove
item_menu-information = Information
item_menu-drop_all = Drop all
item_menu-register-as-shortcut = Register as shortcut
item_menu-select-building = Select building
tile-menu-chop = Chop a tree
tile-menu-down-stairs = Go down the stairs
tile-menu-enter-site = Enter this site
tile-menu-enter-wilderness = Enter wilderness
tile-menu-exit-to-region-map = Exit to region map
tile-menu-deconstruct = Deconstruct
tile-menu-harvest = Harvest
tile-menu-information = Information
tile-menu-target = Target
tile-menu-move-to-next-map = Move to next map
tile-menu-pick-up-items = Pick up items
tile-menu-start-centering = Centering
tile-menu-stop-centering = Stop centering
tile-menu-up-stairs = Go up the stairs
register_shortcut = Register shortcut ({$i})
