creation-start = Start
dialog-choice-close = Close
dialog-choice-exit = Exit
dialog-choice-exit_game = Exit Game
dialog-choice-loadgame = Load Game
dialog-choice-newgame = New Game
dialog-choice-save_game = Save Game
tile-menu-chop = Chop a tree
tile-menu-down-stairs = Go down the stairs
tile-menu-enter-site = Enter this site
tile-menu-exit-to-region-map = Exit to region map
tile-menu-infomation = Infomation
tile-menu-target = Target
tile-menu-move-to-next-map = Move to next map
tile-menu-pick-up-items = Pick up items
tile-menu-start-centering = Centering
tile-menu-stop-centering = Stop centering
tile-menu-up-stairs = Go up the stairs
