tab_text-chara_stats = Stats
tab_text-chara_skills = Skills
tab_text-creation_art = Art
tab_text-creation_construction = Build
tab_text-creation_cooking = Cook
tab_text-creation_craft = Craft
tab_text-creation_pharmacy = Pharmacy
tab_text-creation_smith = Smith
tab_text-item_list = List
tab_text-item_drop = Drop
tab_text-item_throw = Throw
tab_text-item_drink = Drink
tab_text-item_eat = Eat
tab_text-item_use = Use
tab_text-item_release = Release
tab_text-item_read = Read
button_text-close = Close
button_text-creation-cancel = Cancel
button_text-creation-start = Start
label_text-status-faction = Faction
label_text-creation-use-facility = Facility to use
label_text-creation-required-facility = Required facility
label_text-creation-no-required-facility = No required facility
label_text-creation-enough-ingredients = Enough ingredients
label_text-creation-not-enough-ingredients = Not enough ingredients
label_text-creation-required_skill = Required Skill
list_item_text-creation-no_ingredient = No available {$group}
