dialog-exit = Rusted Ruinsを終了しますか?
dialog-exit_to_regionmap = リージョンマップに戻りますか?
dialog-gameover = やられてしまった…。
dialog-move_floor = この階から移動しますか?
dialog-enter_site = {$site_name}に入りますか?
dialog-undertake_quest = このクエストを受諾しますか?
newgame-choose_class = クラスを選択して下さい
newgame-input_player_name = プレイヤー名を入力して下さい
newgame-player_info = 以下のキャラクターでゲームを始めますか？
